# syntax=docker/dockerfile:1.7
#
# Build context is this repository, plus two named contexts for the unpublished sibling packages:
#
#   docker build -t studio \
#     --build-context runtimepkgs=../runtime \
#     --build-context contractspkgs=../contracts .
#
# Both extra contexts are temporary. Once the @cloudsforge/* packages are published (AD-02),
# package.json takes registry versions, the COPY lines marked below are deleted, the flags go
# away, and this becomes an ordinary single-context build. Nothing else changes.
#
# They are named `runtimepkgs`/`contractspkgs` rather than `runtime`/`contracts` because a build
# context and a build stage share one namespace, and the final stage below is called `runtime`.
#
# `contractspkgs` arrives with this change and every other service already had it. The shared
# workflow has always passed BOTH contexts (micro-org `service-ci.yml`), so the omission cost
# nothing until the day this repository first imported a contracts package — measured 2026-08-11,
# that day, as `TS2307: Cannot find module '@cloudsforge/contracts-events'` from `pnpm typecheck`
# inside the image, on a branch whose repository-level typecheck was green. That gap is the whole
# reason the line is worth a comment: the image build typechecks against a DIFFERENT tree than the
# workspace does, and only the image build was ever going to notice.

# ----------------------------------------------------------------------------------- deps
FROM node:22-slim AS deps
# Pin pnpm in the image. The sibling workspaces are installed before this service's own
# package.json is copied, so corepack has no packageManager field to read at that point and
# would otherwise grab whatever is latest and then refuse to switch to the 11.9.0 the
# siblings pin.
RUN corepack enable && corepack prepare pnpm@11.9.0 --activate
WORKDIR /app

# Temporary: the link: dependencies resolve to ../runtime and ../contracts relative to this
# directory, so the packages must exist at those paths inside the image for the lockfile to stay
# frozen.
COPY --from=runtimepkgs package.json pnpm-workspace.yaml pnpm-lock.yaml /runtime/
COPY --from=runtimepkgs packages /runtime/packages
COPY --from=contractspkgs package.json pnpm-workspace.yaml pnpm-lock.yaml /contracts/
COPY --from=contractspkgs packages /contracts/packages

# Install the siblings' OWN dependencies first. `link:` uses the sibling as-is and does not
# manage its dependency tree, so /runtime's and /contracts' node_modules must exist independently —
# both for `tsc` to resolve the sibling source it typechecks (jose, @opentelemetry/api) and
# for `node --import tsx` to load @cloudsforge/* at run time. Without this the image builds a
# set of @cloudsforge symlinks that point at source which cannot resolve its own imports.
RUN --mount=type=cache,id=pnpm-store,target=/pnpm-store,sharing=locked \
    pnpm --dir /runtime install --frozen-lockfile --config.store-dir=/pnpm-store \
 && pnpm --dir /contracts install --frozen-lockfile --config.store-dir=/pnpm-store

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
# `--frozen-lockfile` is the point of the step: a build that silently resolves a different
# dependency tree from the one CI tested is a build whose provenance means nothing.
RUN --mount=type=cache,id=pnpm-store,target=/pnpm-store,sharing=locked \
    pnpm install --frozen-lockfile --config.store-dir=/pnpm-store

# ----------------------------------------------------------------------------------- build
# `tsc --noEmit` rather than an emit: tsx runs the TypeScript sources directly, exactly as every
# service in the estate already does. What this stage buys is that a type error fails the image
# build instead of the first request.
FROM deps AS build
COPY tsconfig.json tsconfig.base.json ./
COPY src ./src
RUN pnpm typecheck

# ----------------------------------------------------------------------------------- runtime
FROM node:22-slim AS runtime
WORKDIR /app

# No corepack, no pnpm, no build toolchain in the final image: fewer things an RCE can reach, and
# nothing at runtime needs them. No image toolchain either — there is no sharp, no ImageMagick and
# no `sips`, because this service measures dimensions from the PNG header rather than resampling.
# That is the whole reason its pipeline runs in CI when asset-forge's cannot.
# `/runtime` and `/contracts` come across too: /app/node_modules holds @cloudsforge/* as symlinks
# into them, so without the targets the links dangle and the first `import '@cloudsforge/db'` fails
# at run time.
COPY --from=build /runtime /runtime
COPY --from=build /contracts /contracts
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
COPY --from=build /app/tsconfig.json /app/tsconfig.base.json ./
COPY --from=build /app/src ./src

# node:22-slim ships an unprivileged `node` user (uid 1000). Generated bytes go to STUDIO_ASSET_ROOT,
# which must be a mounted volume the deploy makes writable — it is deliberately NOT baked into the
# image, because an asset written into a container layer is an asset lost on the next deploy.
USER node

# No secret is baked in, and none may be: every value in src/env.ts is supplied by the deploy at
# run time. There is no ENV line for one here on purpose. AZURE_FOUNDRY_API_KEY in particular is a
# spend credential and belongs in a secret, never in an image or in `docker inspect`.
ENV NODE_ENV=production
# 4015 — this service's own default, from `src/env.ts`'s `integer(source, 'PORT', 4015, …)`.
#
# It said 4012, which is a port no file in this repository names: `.env.example` says 4015 and
# `.github/workflows/ci.yml` passes `port: 4015` to the shared workflow, and the shared workflow
# checks those two against each other but never looks at this line. EXPOSE publishes nothing and
# binds nothing, so the wrong number cost nobody an outage — it cost whoever read it next.
EXPOSE 4015

# The health endpoints are for the orchestrator, not for the image: the balancer probes /readyz and
# the restart policy probes /livez. A HEALTHCHECK here would duplicate that in a second place that
# then drifts.

# The migrator is a SEPARATE one-shot process — `node --import tsx src/migrator.ts` — run as an
# init container or a Kubernetes Job before this ever starts. It is deliberately not invoked here:
# below SCHEMA_VERSION the `credit_accounts_within_cap` CHECK may not exist, and that constraint is
# what makes the spend cap true rather than advisory. A service that could create it at boot is a
# service that could start without it. `index.ts` asserts the schema version and refuses to serve
# below it.
CMD ["node", "--import", "tsx", "src/index.ts"]
